export const shows = [
  {
    title: 'Breaking Bad',
    genre: 'drama',
    mood: 'intense',
    episodeLength: '45-60 min',
    seasons: 5,
    totalEpisodes: 62,
    platforms: ['Netflix'],
    popularity: 'world-renowned',
  },
  {
    title: 'The Office',
    genre: 'comedy',
    mood: 'funny',
    episodeLength: '15-30 min',
    seasons: 9,
    totalEpisodes: 201,
    platforms: ['Netflix', 'Peacock'],
    popularity: 'fans-love',
  },
  {
    title: 'Stranger Things',
    genre: 'sci-fi',
    mood: 'thrilling',
    episodeLength: '45-60 min',
    seasons: 4,
    totalEpisodes: 34,
    platforms: ['Netflix'],
    popularity: 'world-renowned',
  },
  {
    title: 'Friends',
    genre: 'comedy',
    mood: 'lighthearted',
    episodeLength: '15-30 min',
    seasons: 10,
    totalEpisodes: 236,
    platforms: ['Netflix', 'Max'],
    popularity: 'fans-love',
  },
  {
    title: 'The Mandalorian',
    genre: 'sci-fi',
    mood: 'adventurous',
    episodeLength: '30-45 min',
    seasons: 3,
    totalEpisodes: 24,
    platforms: ['Disney+'],
    popularity: 'fans-love',
  },
  {
    title: 'Game of Thrones',
    genre: 'drama',
    mood: 'intense',
    episodeLength: '45-60 min',
    seasons: 8,
    totalEpisodes: 73,
    platforms: ['Max'],
    popularity: 'world-renowned',
  },
  {
    title: 'The Crown',
    genre: 'drama',
    mood: 'thoughtful',
    episodeLength: '45-60 min',
    seasons: 6,
    totalEpisodes: 60,
    platforms: ['Netflix'],
    popularity: 'fans-love',
  },
  {
    title: 'Black Mirror',
    genre: 'sci-fi',
    mood: 'mind-bending',
    episodeLength: '45-60 min',
    seasons: 6,
    totalEpisodes: 27,
    platforms: ['Netflix'],
    popularity: 'cult-classic',
  },
  {
    title: 'Ted Lasso',
    genre: 'comedy',
    mood: 'wholesome',
    episodeLength: '30-45 min',
    seasons: 3,
    totalEpisodes: 34,
    platforms: ['Apple TV+'],
    popularity: 'fans-love',
  },
  {
    title: 'The Witcher',
    genre: 'fantasy',
    mood: 'adventurous',
    episodeLength: '45-60 min',
    seasons: 3,
    totalEpisodes: 24,
    platforms: ['Netflix'],
    popularity: 'fans-love',
  },
  {
    title: 'Succession',
    genre: 'drama',
    mood: 'intense',
    episodeLength: '45-60 min',
    seasons: 4,
    totalEpisodes: 39,
    platforms: ['Max'],
    popularity: 'world-renowned',
  },
  {
    title: 'The Bear',
    genre: 'drama',
    mood: 'intense',
    episodeLength: '15-30 min',
    seasons: 2,
    totalEpisodes: 18,
    platforms: ['Max'],
    popularity: 'fans-love',
  },
  {
    title: 'Severance',
    genre: 'sci-fi',
    mood: 'mind-bending',
    episodeLength: '45-60 min',
    seasons: 1,
    totalEpisodes: 9,
    platforms: ['Apple TV+'],
    popularity: 'cult-classic',
  },
  {
    title: 'Only Murders in the Building',
    genre: 'mystery',
    mood: 'funny',
    episodeLength: '30-45 min',
    seasons: 3,
    totalEpisodes: 30,
    platforms: ['Max'],
    popularity: 'fans-love',
  },
  {
    title: "The Queen's Gambit",
    genre: 'drama',
    mood: 'focused',
    episodeLength: '30-45 min',
    seasons: 1,
    totalEpisodes: 7,
    platforms: ['Netflix'],
    popularity: 'world-renowned',
  },
  {
    title: 'Westworld',
    genre: 'sci-fi',
    mood: 'mind-bending',
    episodeLength: '45-60 min',
    seasons: 4,
    totalEpisodes: 36,
    platforms: ['Max'],
    popularity: 'cult-classic',
  },
  {
    title: 'Parks and Recreation',
    genre: 'comedy',
    mood: 'wholesome',
    episodeLength: '15-30 min',
    seasons: 7,
    totalEpisodes: 125,
    platforms: ['Netflix', 'Peacock'],
    popularity: 'fans-love',
  },
  {
    title: 'Chernobyl',
    genre: 'drama',
    mood: 'thoughtful',
    episodeLength: '45-60 min',
    seasons: 1,
    totalEpisodes: 5,
    platforms: ['Max'],
    popularity: 'world-renowned',
  },
  {
    title: 'The Expanse',
    genre: 'sci-fi',
    mood: 'adventurous',
    episodeLength: '45-60 min',
    seasons: 6,
    totalEpisodes: 62,
    platforms: ['Prime Video'],
    popularity: 'cult-classic',
  },
  {
    title: 'Barry',
    genre: 'drama',
    mood: 'dark',
    episodeLength: '30-45 min',
    seasons: 4,
    totalEpisodes: 32,
    platforms: ['Max'],
    popularity: 'fans-love',
  },
  {
    title: 'Fleabag',
    genre: 'comedy',
    mood: 'emotional',
    episodeLength: '15-30 min',
    seasons: 2,
    totalEpisodes: 12,
    platforms: ['Prime Video'],
    popularity: 'world-renowned',
  },
  {
    title: 'True Detective',
    genre: 'crime',
    mood: 'dark',
    episodeLength: '45-60 min',
    seasons: 4,
    totalEpisodes: 24,
    platforms: ['Max'],
    popularity: 'cult-classic',
  },
  {
    title: "Schitt's Creek",
    genre: 'comedy',
    mood: 'wholesome',
    episodeLength: '15-30 min',
    seasons: 6,
    totalEpisodes: 80,
    platforms: ['Netflix', 'Prime Video'],
    popularity: 'fans-love',
  },
  {
    title: 'Narcos',
    genre: 'crime',
    mood: 'intense',
    episodeLength: '45-60 min',
    seasons: 3,
    totalEpisodes: 30,
    platforms: ['Netflix'],
    popularity: 'fans-love',
  },
];
